name: test-helloworld
version: git
summary: Test
description: |
  Test Hello World in python.
base: core18
confinement: strict
grade: stable

parts:
  test-helloworld:
    plugin: python
    python-version: python3
    source: .

apps:
  test-helloworld:
    command: helloworld
